# Site settings
title: Inkling
description: >
    A personal blog for Gordon M. Celesta about *NIX, human-computer interaction, web design, and other odds-n-sods...

CDN: "http://fastly.ink.sapo.pt/3.1.10"

#url: "http://gordon.celesta.me"
email: gordo@sdf.lonestar.org
twitter_username: va7sdf
github_username: va7sdf
bitbucket_username: va7sdf
linkedin_username: va7sdf

rss: true

# home page layout (recommend < 4 small)
large_excerpts: 1
small_excerpts: 4

# Build settings
markdown: kramdown
future: false

kramdown:
    input: GFM
defaults:
  -
    scope:
      path: _posts
      type: posts
    values:
      author: "Gordon M. Celesta"
      layout: default
