# Site settings
title: Inkling
description: >
    A personal blog for Gordon M. Celesta about *NIX, human-computer interaction, web design, and other odds-n-sods...

CDN: "http://fastly.ink.sapo.pt/3.1.10"

url: "http://gordon.celesta.me"
email: gordo@sdf.lonestar.org
twitter_username: va7sdf
github_username:  va7sdf

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: _posts
      type: posts
    values:
      author: "Gordon M. Celesta"
      layout: default
